Wheeler 36, 37, Appendices
friends-library/daniel-wheeler pull request #13
Opened 2019-03-09 04:37 UTC by maijapapaya

@jaredh159 @Henderjay

2019-03-09 04:40 UTC, maijapapaya commented on journal/modernized/40-chapter-37.adoc
> +it was thought that the following sketch which occurs after the decease of our brother,
So I"m not sure what happened here.....I don't remember if I did something on the computer or what, but the text didn't match the original anymore, almost like I copied and pasted something, but I didn't know how to fix it so I just left it. I was thinking an "undo" button would be nice? Haha

2019-03-09 04:41 UTC, maijapapaya commented on journal/modernized/40-chapter-37.adoc
> +of making preparations for my departure there.
Is this an acceptable update of thitherwards?

2019-03-11 17:27 UTC, Henderjay requested changes
Hey Maija, great work! There were a couple places where I think the control Z error that Jared mentioned in the asciidoc channel messed things up. :(  A couple other minor things. Thanks!!

2019-03-11 17:27 UTC, Henderjay commented on journal/modernized/39-chapter-36.adoc
> +//Vouchsafed has been left in this whole book. It was never circled, but I had come across it before. Is it too late to change it now? Should I just leave this one too?
I think we can leave vouchsafe for now throughout the book. If we decide to change that in the future in modernized versions, we can do it all at once with Jared's nifty tools.

2019-03-11 17:27 UTC, Henderjay commented on journal/modernized/39-chapter-36.adoc
> +but rather have a tendency to promote His cause, by keeping me clothed with humility,"`Awake, O! north wind,
Hmm... something funny happened here. Somehow another line of text got replaced for the original line 555 and 556. I'm guessing that either you made a copy/paste mistake, OR you used undo/redo feature on the editor, which Jared says is kinda wonky and sometimes messes things up (he has it on his list to fix that). I'm not sure what the original mistake was, but the two lines prior to "Awake, O north wind..." have to be put back in.👍🏻

2019-03-11 17:27 UTC, Henderjay commented on journal/modernized/39-chapter-36.adoc
> +//arrear is circled, but I'm not sure it needs to be changed?
Its an old expression, but I think people probably get the meaning. Definitely leave it in the original... and I can't think of a way to easily change the modernized without rewording the sentence. So I'd say leave it here too.

2019-03-11 17:27 UTC, Henderjay commented on journal/modernized/40-chapter-37.adoc
> +of making preparations for my departure there.
Yup, that looks good to me in this context. There might be some other contexts where another word would fit better. But here `there` works👍🏻

2019-03-11 17:27 UTC, Henderjay commented on journal/modernized/40-chapter-37.adoc
> +it was thought that the following sketch which occurs after the decease of our brother,
This looks like what happened above, and I just slacked with Jared about it... he definitely thinks its a bug in the editor which he's going to fix that happens when you hit control Z to undo something.  Sorry about that!  To fix this, you'll have to just remove `it was thought that the following sketch which occurs after the decease of our brother,` and replace it with  `He frequently engaged in fervent prayer for patience and support,`

2019-03-11 17:27 UTC, Henderjay commented on journal/modernized/40-chapter-37.adoc
> +//"gross" above is circled. Not sure what I should change it to, if at all.
Maybe change it to, `You must accept it as it is, ...` His point is that its a short, kinda weak attempt at communicating because he was so ill.

2019-03-11 17:27 UTC, Henderjay commented on journal/modernized/42-appendix.adoc
> +//Note here to omit Appendix B
hmm... I think we can leave it as is.  It just basically states that they didn't have room to put in what they were planning on putting in. Jess thought that maybe we should just take it out... but I don't know that that is necessary.

2019-03-11 17:27 UTC, Henderjay commented on journal/modernized/42-appendix.adoc
> +//Should this apostrophe be kept here? It's in the original.
Nope, I think that's an error. You can remove it.

2019-03-11 17:27 UTC, Henderjay commented on journal/modernized/42-appendix.adoc
> +//Is this $2 per lb?
I think so... but I'm not totally sure. I think I feel safer just leaving it as is.

2019-03-11 17:27 UTC, Henderjay commented on journal/modernized/42-appendix.adoc
> +//And would this be 12 cents? I also may have pasted this in a couple of other placees on accident.
same here... I'm not totally certain, and would probably just leave it.

2019-03-11 17:27 UTC, Henderjay commented on journal/modernized/42-appendix.adoc
> +// I'm not sure what that line above is. "marai" in 799 in the book is underlined, not sure what it means.
I remember that there were a bunch of "islander" terms that were used in the latter part of this book. I think this is one of them....maybe the name for the place where the islanders did human sacrifice previously. I would leve it.

2019-03-11 17:27 UTC, Henderjay commented on journal/modernized/42-appendix.adoc
> +//Adroit here isn't archaic, but I had never heard of it. Should I leave it?
I would probably leave it.

2019-03-11 17:27 UTC, Henderjay commented on journal/modernized/42-appendix.adoc
> +//pa above is circled, but it matches the original. Not sure what it means.
Ok, if it matches the original, then its probably just an island term. We can leave it.

2019-03-11 17:27 UTC, Henderjay commented on journal/original/42-appendix.adoc
> +
Is this a blank line that needs to be removed?

2019-03-11 17:27 UTC, Henderjay commented on journal/original/42-appendix.adoc
> +
same here? Another blank line?

2019-03-12 14:04 UTC, Henderjay commented
Looks great Maija, I'm going to merge.

2019-03-12 14:04 UTC, closed without merging